### PR TITLE
docs: fix `Envrionment` typo

### PR DESCRIPTION
**Pull request by Cherry**

### CODE REVIEW

**Review by williamhorning — APPROVED** [review]
great code @Cherry! looks like an epic feature

**Comment by WalshyDev** [comment]
Who dis?

**Comment by KianNH** [comment]
> Who dis?

docs: fix `dis` typo

**Comment by williamhorning** [comment]
> > Who dis?
> 
> docs: fix `dis` typo

Docs: fix `docs` case

**Pull request merged**
